server:
  port: 8080

spring:
  config:
    import: classpath:database.properties  # 引入 resources 目录下的文件

  datasource:
    url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: admin
    password: admin

jwt:
  secret: D3j9kQ7mXn2rY5vB8wE1hG4sJ6uL0pO3iA8cF7tR2yU5nW1qK4zM9xV6bC0fH3

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml